{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hfpathsim.fullname" . }}
  labels:
    {{- include "hfpathsim.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "hfpathsim.api.serviceName" . }}
                port:
                  number: {{ .Values.api.service.port }}
          {{- if .Values.web.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "hfpathsim.web.serviceName" . }}
                port:
                  number: {{ .Values.web.service.port }}
          {{- end }}
{{- end }}
